### ISSUE TITLE
get some records

### ISSUE THREAD

**Issue by loreneteddy93** [rahil471/search-sort-and-pagination-angularjs#1]
hi friend,
Now i want to paging as following:
– I dont want get all record, because it’s very slow if i have 1mili records.
– I want to each time get some records(10). when user click to page index, it is go to db and get again

**Comment by rahil471** [comment]
Here is the tutorial I've written, 
http://code.ciphertrick.com/2015/08/31/server-side-pagination-in-angularjs/ 
Not sure if its any help to you now.
Excuse me for the delayed reply, not sure why github never notified me.
